name: Create and publish a nuget package

on:
  push:
    branches: ["master"]

env:
  GITHUB_USER: ${{ github.actor }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build maven
        working-directory: JDBC.NET.Bridge
        run: mvn clean package

      - name: Package nuget
        working-directory: JDBC.NET.Data
        run: dotnet pack --configuration Release
      
      - name: Publish nuget
        working-directory: JDBC.NET.Data
        run: dotnet nuget push "bin/Release/JDBC.NET.Data.*.nupkg" --source "github"